### PR TITLE
fix test on Elixir version 1.4 or later

### LINKED ISSUE #8: Anonymous function has been enclosed in parentheses after Elixir 1.4
```
  1) test fn expr not supported (PowerAssertAssertionTest)
     test/power_assert_test.exs:859
     Assertion with == failed
     code:  expect == error.message()
     left:  "fn x -> x == 1 end.(y)\n                   ||\n                   |2\n                   false"
     right: "(fn x -> x == 1 end).(y)\n                      |\n                      2"
     stacktrace:
       test/power_assert_test.exs:873: (test)
```

### PR DESCRIPTION
**Pull request by ma2gedev**
close #8

### CODE REVIEW

File: lib/power_assert/assertion.ex [hunk 1]
```diff
@@ -219,7 +219,7 @@ defmodule PowerAssert.Assertion do
   defp collect_position({{:., _, [l]}, _, _} = ast, detector) do
     func_call = Macro.to_string(ast)
     match_indexes = match_indexes_in_code(func_call, detector.code, :function_boundary)
-    length = Macro.to_string(l) |> String.length
+    length = function_expression(l) |> String.length
```
Comment (ma2gedev) [inline lib/power_assert/assertion.ex:222]: Use a function call when a pipeline is only one function long

**Comment by ma2gedev** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 33 possible new issues (including those that may have been commented here).
* 2 fixed issues! 🎉

You can see more details about this review at https://ebertapp.io/github/ma2gedev/power_assert_ex/pulls/12.
